apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: spring-login-api
spec:
  selector:
    matchLabels:
      app: spring-login-api
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: spring-login-api
    spec:
      containers:
        - name: spring-login-api
          image: arshdang/spring_login_api:latest
          # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 90

# The port that the container is running on in the cluster