apiVersion: v1
kind: Service
metadata:
  name: spring-login-api-svc
  labels:
    app: spring-login-api
spec:
  selector:
    app: spring-login-api
  ports:
    - protocol: TCP
      port: 8080       # Port that the service exposes inside the cluster
      targetPort: 8080 # Port that the Spring Boot pod listens on
  type: NodePort      # Exposes the service outside the cluster
# Only accessible within the cluster